.bail ON
.mode columns
.headers on
.nullvalue NULL

PRAGMA FOREIGN_KEYS=ON;

DROP TABLE IF EXISTS CLUBE;
DROP TABLE IF EXISTS CAMPO;
DROP TABLE IF EXISTS ESCALAO;
DROP TABLE IF EXISTS EQUIPA;
DROP TABLE IF EXISTS LIGA;
DROP TABLE IF EXISTS JOGO;
DROP TABLE IF EXISTS PESSOA;

DROP TABLE IF EXISTS ARBITRO;
DROP TABLE IF EXISTS JOGADOR;
DROP TABLE IF EXISTS EVENTO;
DROP TABLE IF EXISTS SUBSTITUICAO;
DROP TABLE IF EXISTS CARTAO;
DROP TABLE IF EXISTS GOLO;
DROP TABLE IF EXISTS GRUPO;
DROP TABLE IF EXISTS PERFIL;
DROP TABLE IF EXISTS NATURALIDADE;

CREATE TABLE CLUBE (
	idClube INTEGER PRIMARY KEY,
	Nome TEXT NOT NULL,
	Regiao TEXT NOT NULL
);

CREATE TABLE CAMPO (
	idCampo INTEGER PRIMARY KEY,
	idClube INTEGER REFERENCES CLUBE(idClube) NOT NULL,
	Localidade TEXT NOT NULL,
	Relvado TEXT NOT NULL
);

CREATE TABLE ESCALAO (
	idEscalao INTEGER PRIMARY KEY,
	FaixaEtaria TEXT NOT NULL,
	Sexo CHAR(1) NOT NULL CHECK ((Sexo='F') or (Sexo='M'))
);

CREATE TABLE EQUIPA (
	idEquipa INTEGER PRIMARY KEY,
	Nome TEXT NOT NULL,
	idClube INTEGER REFERENCES CLUBE(idClube) NOT NULL,
	idEscalao INTEGER REFERENCES ESCALAO(idEscalao) NOT NULL
);

CREATE TABLE LIGA (
	idLiga INTEGER PRIMARY KEY,
	Nome TEXT NOT NULL,
	Regiao TEXT NOT NULL
);

CREATE TABLE JOGO (
	idJogo INTEGER PRIMARY KEY,
	Data DATE NOT NULL,
	GolosCasa INTEGER,
	GolosFora INTEGER,
	idEquipaVisitante INTEGER REFERENCES EQUIPA(idEquipa) NOT NULL,
	idEquipaVisitada INTEGER REFERENCES EQUIPA(idEquipa) NOT NULL,
	idLiga INTEGER REFERENCES LIGA(idLiga) NOT NULL,
	idCampo INTEGER REFERENCES CAMPO(idCampo) NOT NULL
);

CREATE TABLE PESSOA (
	idPessoa INTEGER PRIMARY KEY,
	Nome TEXT NOT NULL,
	Nacionalidade TEXT NOT NULL,
	Peso INTEGER NOT NULL CHECK (Peso > 0),
	Idade INTEGER NOT NULL CHECK (Idade > 0)
);

CREATE TABLE ARBITRO (
	idPessoa INTEGER REFERENCES PESSOA(idPessoa) NOT NULL
);

CREATE TABLE JOGADOR (
	idPessoa INTEGER REFERENCES PESSOA(idPessoa) NOT NULL,
	idEquipa INTEGER REFERENCES EQUIPA(idEquipa)
);

CREATE TABLE EVENTO (
	idEvento INTEGER PRIMARY KEY,
	idJogo INTEGER REFERENCES JOGO(idJogo) NOT NULL,
	idJogador INTEGER REFERENCES Pessoa(idPessoa) NOT NULL,
	Minuto INTEGER NOT NULL CHECK((Minuto>=0) and (Minuto <= 90))
);

CREATE TABLE SUBSTITUICAO (
	idEvento INTEGER REFERENCES EVENTO(idEvento) NOT NULL,
	idEntra INTEGER REFERENCES JOGADOR(idEntra) NOT NULL,
	idSai INTEGER REFERENCES JOGADOR(idEntra) NOT NULL
);

CREATE TABLE CARTAO (
	idCartao INTEGER PRIMARY KEY,
	Cor TEXT NOT NULL,
	Razao TEXT NOT NULL,
	idEvento INTEGER REFERENCES EVENTO(idEvento) NOT NULL
);

CREATE TABLE GOLO (
	idGolo INTEGER PRIMARY KEY,
	Baliza TEXT NOT NULL,
	idEvento INTEGER REFERENCES EVENTO(idEvento) NOT NULL
);